package View;

public class JFmenuPrincipal extends javax.swing.JFrame {

    public JFmenuPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnGestionarCandidato = new javax.swing.JButton();
        btnAgregarVotantes = new javax.swing.JButton();
        btnVotar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        btnGestionarEleccion = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Menú principal");
        setBackground(java.awt.SystemColor.control);
        setResizable(false);

        jPanel1.setBackground(java.awt.SystemColor.window);

        btnGestionarCandidato.setBackground(java.awt.SystemColor.controlHighlight);
        btnGestionarCandidato.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnGestionarCandidato.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/usuarios.png"))); // NOI18N
        btnGestionarCandidato.setText("Gestionar candidatos");
        btnGestionarCandidato.setFocusPainted(false);
        btnGestionarCandidato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGestionarCandidatoActionPerformed(evt);
            }
        });

        btnAgregarVotantes.setBackground(java.awt.SystemColor.controlHighlight);
        btnAgregarVotantes.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnAgregarVotantes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/agregar.png"))); // NOI18N
        btnAgregarVotantes.setText("Agregar votantes");
        btnAgregarVotantes.setFocusPainted(false);
        btnAgregarVotantes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarVotantesActionPerformed(evt);
            }
        });

        btnVotar.setBackground(new java.awt.Color(204, 255, 204));
        btnVotar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnVotar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/urna-boleta.png"))); // NOI18N
        btnVotar.setText("Votar");
        btnVotar.setFocusPainted(false);
        btnVotar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVotarActionPerformed(evt);
            }
        });

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/votaciones.png"))); // NOI18N

        btnGestionarEleccion.setBackground(java.awt.SystemColor.controlHighlight);
        btnGestionarEleccion.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnGestionarEleccion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/votacion.png"))); // NOI18N
        btnGestionarEleccion.setText("Gestionar elección");
        btnGestionarEleccion.setFocusPainted(false);
        btnGestionarEleccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGestionarEleccionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(126, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 546, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(154, 154, 154))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(114, 114, 114)
                .addComponent(btnGestionarCandidato)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnGestionarEleccion, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnAgregarVotantes)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnVotar, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(177, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(163, 163, 163)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(btnGestionarCandidato, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAgregarVotantes, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnGestionarEleccion, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnVotar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(109, 109, 109))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnAgregarVotantesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarVotantesActionPerformed
        JFagregarVotantes menuAV = new JFagregarVotantes();
        menuAV.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnAgregarVotantesActionPerformed

    private void btnGestionarCandidatoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGestionarCandidatoActionPerformed
        JFgestionarCandidatos menuG = new JFgestionarCandidatos();
        menuG.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnGestionarCandidatoActionPerformed

    private void btnGestionarEleccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGestionarEleccionActionPerformed
        JFgestionarEleccion menuGE = new JFgestionarEleccion();
        menuGE.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnGestionarEleccionActionPerformed

    private void btnVotarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVotarActionPerformed
        JFvotacion menuV = new JFvotacion();
        menuV.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnVotarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFmenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFmenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFmenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFmenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFmenuPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregarVotantes;
    private javax.swing.JButton btnGestionarCandidato;
    private javax.swing.JButton btnGestionarEleccion;
    private javax.swing.JButton btnVotar;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
